### ISSUE TITLE
Pruned version

### ISSUE THREAD

**Issue by mariocynicys** [getumbrel/umbrel-bitcoin#2]
This issue was discussed before in [here](https://github.com/getumbrel/umbrel/issues/105) but ended up not being implemented for the sake of other apps' health.

Making another version of this `umbrel-bitcoin` might be a wiser solution. Electrs (and other apps that depend on a non-pruned node) can then depend on the non-pruned version and apps that support pruned nodes (like lnd, cln, etc...) can depend on either versions.

Having a node, besides being beneficial for the usage of some apps, is essential for one's sovereignty on the blockchain. And pruning would allow more people to run nodes.

**Comment by patmillertime** [comment]
Pruning is now implemented in Umbrel btw

**Comment by mariocynicys** [comment]
@patmillertime Yeah I updated it a while ago. Thanks!
