### ISSUE TITLE
Feature to modify mempool memory size

### ISSUE THREAD

**Issue by patmillertime** [getumbrel/umbrel-bitcoin#4]
Hi there, it would be nice if there was an advanced feature in the Bitcoin Core node UI to modify the amount of memory dedicated to the mempool. Ideally it could be set to 0mb up to 1000mb (suggest keeping the current default at 300mb)

**Comment by nmfretz** [comment]
Hi @patmillertime, this has been added to the recent 0.5.0 update! You can change `maxmempool` in Advanced Settings under the "Optimization" Category along with other mempool related settings:

<img width="813" alt="image" src="https://github.com/getumbrel/umbrel-bitcoin/assets/85373263/6109a16e-3e3e-4f60-b9e5-dadfda98208f">

**Comment by pmiller-cs** [comment]
Thank you!

**Comment by patmillertime** [comment]
Thank you!
